name: Slack Notify on Star
on: watch
jobs:
  star-notify:
    name: Notify slack on star
    runs-on: ubuntu-latest
    steps:
    - name: Get current star count
      run: |
        echo ::set-env name=STARS::$(curl --silent 'https://api.github.com/repos/layer5io/layer5-ng' -H 'Accept: application/vnd.github.preview' | jq '.watchers_count')
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CSK7N9TGX\",\"text\":\"Someone just starred Layer5-ng! (https://github.com/layer5io/layer5-ng/stargazers) Total stars: ${{env.STARS}}\"}'
        # command: echo "Now at ${{env.STARS}} stars."
# name: Slack Notify on Star
# on: watch
# jobs:
#   slackNotification:
#     name: Count stars
#     runs-on: ubuntu-latest
#     steps:
#     - name: Get current star count
#       run: |
#         echo ::set-env name=STARS::$(curl --silent 'https://api.github.com/repos/layer5io/meshery' -H 'Accept: application/vnd.github.preview' | jq '.watchers_count')
#     - name: Slack Notification
#       env:
#         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#       uses: rtCamp/action-slack-notify@v2.0.2
#       with:
#         args: '{\"channel\":\"CSK7N9TGX\",\"text\":\"Someone just starred Meshery! (https://github.com/layer5io/meshery/stargazers) Total stars: ${{env.STARS}}\"}'
#         command: echo "Now at ${{env.STARS}} stars."
